baseUrl = "https://joeytat.github.io/"
languageCode = "zh-cn"
title = "Dev Log"
theme = "hello-friend"
paginate = 5
googleAnalytics = "UA-131363452-1"

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # "light" or "dark"
  defaultTheme = "light"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # Show reading time in minutes for posts
  showReadingTime = false

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  # toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  rssFullText = true

[params.logo]
	logoText = "Joeytat's Devlog"
#   or
#
#   path = "/img/your-example-logo.svg"
#   alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "Archive"
    name = "存档"
    url = "/archive"

#	[[menu.main]]
#		identifier = "contact"
#		name = "Contact"
#		url = "/contact"
